// Universo de tickers cobertos pela análise de /mercado.
// Listas escolhidas pelos critérios de market cap / liquidez:
//   - ACOES_BR : Top 60 do Ibovespa
//   - FIIS     : Top 50 FIIs por liquidez/PL
//   - ACOES_US : Top 50 do S&P 500 por market cap
//   - REITS    : Top 50 REITs americanos por market cap

export const ACOES_BR = [
  { ticker: "PETR4", nome: "Petrobras",               setor: "Petróleo e Gás" },
  { ticker: "VALE3", nome: "Vale",                    setor: "Mineração" },
  { ticker: "ITUB4", nome: "Itaú Unibanco",           setor: "Bancos" },
  { ticker: "BBDC4", nome: "Bradesco",                setor: "Bancos" },
  { ticker: "BBAS3", nome: "Banco do Brasil",         setor: "Bancos" },
  { ticker: "ABEV3", nome: "Ambev",                   setor: "Bebidas" },
  { ticker: "WEGE3", nome: "WEG",                     setor: "Industrial" },
  { ticker: "SUZB3", nome: "Suzano",                  setor: "Papel e Celulose" },
  { ticker: "ELET3", nome: "Eletrobras",              setor: "Utilities" },
  { ticker: "B3SA3", nome: "B3",                      setor: "Financeiro" },
  { ticker: "ITSA4", nome: "Itaúsa",                  setor: "Holding" },
  { ticker: "RENT3", nome: "Localiza",                setor: "Aluguel de Veículos" },
  { ticker: "PRIO3", nome: "PetroRio",                setor: "Petróleo e Gás" },
  { ticker: "RADL3", nome: "Raia Drogasil",           setor: "Varejo Saúde" },
  { ticker: "EQTL3", nome: "Equatorial",              setor: "Utilities" },
  { ticker: "JBSS3", nome: "JBS",                     setor: "Alimentos" },
  { ticker: "GGBR4", nome: "Gerdau",                  setor: "Siderurgia" },
  { ticker: "VIVT3", nome: "Vivo",                    setor: "Telecom" },
  { ticker: "RAIL3", nome: "Rumo",                    setor: "Logística" },
  { ticker: "TIMS3", nome: "TIM",                     setor: "Telecom" },
  { ticker: "EMBR3", nome: "Embraer",                 setor: "Industrial" },
  { ticker: "UGPA3", nome: "Ultrapar",                setor: "Distribuição" },
  { ticker: "CSAN3", nome: "Cosan",                   setor: "Conglomerado" },
  { ticker: "VBBR3", nome: "Vibra Energia",           setor: "Distribuição" },
  { ticker: "HAPV3", nome: "Hapvida",                 setor: "Saúde" },
  { ticker: "RDOR3", nome: "Rede D'Or",               setor: "Saúde" },
  { ticker: "LREN3", nome: "Lojas Renner",            setor: "Varejo" },
  { ticker: "ASAI3", nome: "Assaí",                   setor: "Varejo" },
  { ticker: "MGLU3", nome: "Magazine Luiza",          setor: "Varejo" },
  { ticker: "KLBN11",nome: "Klabin",                  setor: "Papel e Celulose" },
  { ticker: "BRFS3", nome: "BRF",                     setor: "Alimentos" },
  { ticker: "CPLE6", nome: "Copel",                   setor: "Utilities" },
  { ticker: "TOTS3", nome: "Totvs",                   setor: "Tecnologia" },
  { ticker: "SBSP3", nome: "Sabesp",                  setor: "Saneamento" },
  { ticker: "CMIG4", nome: "Cemig",                   setor: "Utilities" },
  { ticker: "CSNA3", nome: "CSN",                     setor: "Siderurgia" },
  { ticker: "CPFE3", nome: "CPFL Energia",            setor: "Utilities" },
  { ticker: "EGIE3", nome: "Engie Brasil",            setor: "Utilities" },
  { ticker: "BBSE3", nome: "BB Seguridade",           setor: "Seguros" },
  { ticker: "PSSA3", nome: "Porto Seguro",            setor: "Seguros" },
  { ticker: "SANB11",nome: "Santander",               setor: "Bancos" },
  { ticker: "MULT3", nome: "Multiplan",               setor: "Shoppings" },
  { ticker: "HYPE3", nome: "Hypera",                  setor: "Farmacêutico" },
  { ticker: "CYRE3", nome: "Cyrela",                  setor: "Construção" },
  { ticker: "EZTC3", nome: "EZTEC",                   setor: "Construção" },
  { ticker: "FLRY3", nome: "Fleury",                  setor: "Saúde" },
  { ticker: "SLCE3", nome: "SLC Agrícola",            setor: "Agronegócio" },
  { ticker: "TAEE11",nome: "Taesa",                   setor: "Utilities" },
  { ticker: "ENGI11",nome: "Energisa",                setor: "Utilities" },
  { ticker: "MRFG3", nome: "Marfrig",                 setor: "Alimentos" },
  // Adicionados — completam top 60
  { ticker: "ENEV3", nome: "Eneva",                   setor: "Utilities" },
  { ticker: "BRAV3", nome: "3R Petroleum",            setor: "Petróleo e Gás" },
  { ticker: "ALOS3", nome: "Allos",                   setor: "Shoppings" },
  { ticker: "CCRO3", nome: "CCR Rodovias",            setor: "Concessões" },
  { ticker: "SMTO3", nome: "São Martinho",            setor: "Agronegócio" },
  { ticker: "CMIN3", nome: "CSN Mineração",           setor: "Mineração" },
  { ticker: "CXSE3", nome: "Caixa Seguridade",        setor: "Seguros" },
  { ticker: "LWSA3", nome: "Locaweb",                 setor: "Tecnologia" },
  { ticker: "POMO4", nome: "Marcopolo",               setor: "Industrial" },
  { ticker: "DXCO3", nome: "Dexco",                   setor: "Industrial" },
];

export const FIIS = [
  // Logística
  { ticker: "HGLG11", nome: "CSHG Logística",           setor: "Logística" },
  { ticker: "BTLG11", nome: "BTG Pactual Logística",    setor: "Logística" },
  { ticker: "VILG11", nome: "Vinci Logística",          setor: "Logística" },
  { ticker: "XPLG11", nome: "XP Log",                   setor: "Logística" },
  { ticker: "BRCO11", nome: "Bresco Logística",         setor: "Logística" },
  { ticker: "GGRC11", nome: "GGR Covepi Renda",         setor: "Logística" },
  { ticker: "LVBI11", nome: "VBI Logístico",            setor: "Logística" },
  { ticker: "SDIL11", nome: "SDI Logístico Rio",        setor: "Logística" },
  // Shoppings
  { ticker: "HGBS11", nome: "CSHG Brasil Shoppings",    setor: "Shoppings" },
  { ticker: "XPML11", nome: "XP Malls",                 setor: "Shoppings" },
  { ticker: "HSML11", nome: "HSI Malls",                setor: "Shoppings" },
  { ticker: "VISC11", nome: "Vinci Shopping Centers",   setor: "Shoppings" },
  { ticker: "MALL11", nome: "Malls Brasil Plural",      setor: "Shoppings" },
  { ticker: "HFOF11", nome: "Hedge Top Fofii",          setor: "Shoppings" },
  // Papel (CRI)
  { ticker: "MXRF11", nome: "Maxi Renda",               setor: "Papel" },
  { ticker: "KNIP11", nome: "Kinea Índices de Preços",  setor: "Papel" },
  { ticker: "IRDM11", nome: "Iridium Recebíveis",       setor: "Papel" },
  { ticker: "RECR11", nome: "REC Recebíveis",           setor: "Papel" },
  { ticker: "RBRR11", nome: "RBR Rendimento High Grade",setor: "Papel" },
  { ticker: "HGCR11", nome: "CSHG Recebíveis",          setor: "Papel" },
  { ticker: "KNCR11", nome: "Kinea Rendimentos",        setor: "Papel" },
  { ticker: "VRTA11", nome: "Fator Verita",             setor: "Papel" },
  { ticker: "KNHY11", nome: "Kinea High Yield",         setor: "Papel" },
  { ticker: "CPTS11", nome: "Capitânia Securities",     setor: "Papel" },
  { ticker: "RBRY11", nome: "RBR Crédito Imobiliário",  setor: "Papel" },
  { ticker: "BCFF11", nome: "BTG Pactual Fund of Funds",setor: "Papel" },
  { ticker: "RBVA11", nome: "Rio Bravo Renda Varejo",   setor: "Papel" },
  { ticker: "FEXC11", nome: "BTG Pactual Fundo de CRI", setor: "Papel" },
  // Renda Urbana / Galpões
  { ticker: "GARE11", nome: "Guardian Real Estate",     setor: "Renda Urbana" },
  { ticker: "TRXF11", nome: "TRX Real Estate",          setor: "Renda Urbana" },
  { ticker: "RZTR11", nome: "Riza Terrax",              setor: "Renda Urbana" },
  // Corporativo / Lajes
  { ticker: "HGRE11", nome: "CSHG Real Estate",         setor: "Corporativo" },
  { ticker: "JSRE11", nome: "JS Real Estate",           setor: "Corporativo" },
  { ticker: "BRCR11", nome: "BTG Pactual Corporate",    setor: "Corporativo" },
  { ticker: "RCRB11", nome: "Rio Bravo Renda Corp.",    setor: "Corporativo" },
  { ticker: "PVBI11", nome: "VBI Prime Properties",     setor: "Corporativo" },
  { ticker: "VINO11", nome: "Vinci Offices",            setor: "Corporativo" },
  // Híbrido / Outros
  { ticker: "KNRI11", nome: "Kinea Renda Imobiliária",  setor: "Híbrido" },
  { ticker: "HGRU11", nome: "CSHG Renda Urbana",        setor: "Híbrido" },
  { ticker: "RBRP11", nome: "RBR Properties",           setor: "Híbrido" },
  { ticker: "ALZR11", nome: "Alianza Trust Renda",      setor: "Híbrido" },
  { ticker: "RBHG11", nome: "RBR High Grade",           setor: "Papel" },
  { ticker: "BBPO11", nome: "BB Progressivo II",        setor: "Renda Urbana" },
  { ticker: "MGFF11", nome: "Mogno Fundo de Fundos",    setor: "Fundo de Fundos" },
  // Saúde / Educação
  { ticker: "HCTR11", nome: "Hectare CE",               setor: "Híbrido" },
  // Agro
  { ticker: "RZAT11", nome: "Riza Arctium Real Estate", setor: "Renda Urbana" },
  // Outros para completar 50
  { ticker: "RECT11", nome: "REC Renda Urbana",         setor: "Renda Urbana" },
  { ticker: "OUJP11", nome: "Ourinvest JPP",            setor: "Papel" },
  { ticker: "VGIP11", nome: "Valora CRI Índice Preços", setor: "Papel" },
  { ticker: "JPPA11", nome: "JPP Capital",              setor: "Papel" },
  { ticker: "URPR11", nome: "Urca Prime Renda",         setor: "Renda Urbana" },
];

export const ACOES_US = [
  // Tech (FAANG+)
  { ticker: "AAPL",  nome: "Apple",              setor: "Tech" },
  { ticker: "MSFT",  nome: "Microsoft",          setor: "Tech" },
  { ticker: "GOOGL", nome: "Alphabet",           setor: "Tech" },
  { ticker: "AMZN",  nome: "Amazon",             setor: "E-commerce" },
  { ticker: "META",  nome: "Meta",               setor: "Tech" },
  { ticker: "NVDA",  nome: "NVIDIA",             setor: "Semicondutores" },
  { ticker: "TSLA",  nome: "Tesla",              setor: "Automotivo" },
  { ticker: "AMD",   nome: "AMD",                setor: "Semicondutores" },
  { ticker: "AVGO",  nome: "Broadcom",           setor: "Semicondutores" },
  { ticker: "TSM",   nome: "TSMC",               setor: "Semicondutores" },
  { ticker: "ORCL",  nome: "Oracle",             setor: "Tech" },
  { ticker: "ADBE",  nome: "Adobe",              setor: "Tech" },
  { ticker: "CRM",   nome: "Salesforce",         setor: "Tech" },
  { ticker: "NFLX",  nome: "Netflix",            setor: "Mídia" },
  { ticker: "DIS",   nome: "Disney",             setor: "Mídia" },
  { ticker: "INTC",  nome: "Intel",              setor: "Semicondutores" },
  { ticker: "CSCO",  nome: "Cisco",              setor: "Tech" },
  { ticker: "TXN",   nome: "Texas Instruments",  setor: "Semicondutores" },
  { ticker: "QCOM",  nome: "Qualcomm",           setor: "Semicondutores" },
  { ticker: "IBM",   nome: "IBM",                setor: "Tech" },
  // Bancos / Financeiro
  { ticker: "JPM",   nome: "JPMorgan",           setor: "Bancos" },
  { ticker: "BAC",   nome: "Bank of America",    setor: "Bancos" },
  { ticker: "WFC",   nome: "Wells Fargo",        setor: "Bancos" },
  { ticker: "GS",    nome: "Goldman Sachs",      setor: "Bancos" },
  { ticker: "MS",    nome: "Morgan Stanley",     setor: "Bancos" },
  { ticker: "V",     nome: "Visa",               setor: "Pagamentos" },
  { ticker: "MA",    nome: "Mastercard",         setor: "Pagamentos" },
  { ticker: "BRK-B", nome: "Berkshire Hathaway", setor: "Holding" },
  // Saúde / Farma
  { ticker: "JNJ",   nome: "Johnson & Johnson",  setor: "Saúde" },
  { ticker: "UNH",   nome: "UnitedHealth",       setor: "Saúde" },
  { ticker: "LLY",   nome: "Eli Lilly",          setor: "Farmacêutico" },
  { ticker: "ABBV",  nome: "AbbVie",             setor: "Farmacêutico" },
  { ticker: "MRK",   nome: "Merck",              setor: "Farmacêutico" },
  { ticker: "PFE",   nome: "Pfizer",             setor: "Farmacêutico" },
  { ticker: "ABT",   nome: "Abbott Laboratories",setor: "Saúde" },
  { ticker: "TMO",   nome: "Thermo Fisher",      setor: "Saúde" },
  // Consumo / Varejo
  { ticker: "WMT",   nome: "Walmart",            setor: "Varejo" },
  { ticker: "COST",  nome: "Costco",             setor: "Varejo" },
  { ticker: "HD",    nome: "Home Depot",         setor: "Varejo" },
  { ticker: "MCD",   nome: "McDonald's",         setor: "Restaurantes" },
  { ticker: "KO",    nome: "Coca-Cola",          setor: "Bebidas" },
  { ticker: "PEP",   nome: "PepsiCo",            setor: "Bebidas" },
  { ticker: "PG",    nome: "Procter & Gamble",   setor: "Consumo" },
  // Energia
  { ticker: "XOM",   nome: "ExxonMobil",         setor: "Petróleo e Gás" },
  { ticker: "CVX",   nome: "Chevron",            setor: "Petróleo e Gás" },
  // Industrial / Defesa
  { ticker: "CAT",   nome: "Caterpillar",        setor: "Industrial" },
  { ticker: "BA",    nome: "Boeing",             setor: "Industrial" },
  { ticker: "GE",    nome: "GE Aerospace",       setor: "Industrial" },
  { ticker: "HON",   nome: "Honeywell",          setor: "Industrial" },
  { ticker: "LMT",   nome: "Lockheed Martin",    setor: "Defesa" },
  { ticker: "RTX",   nome: "RTX (Raytheon)",     setor: "Defesa" },
];

export const REITS = [
  // Telecom (Towers)
  { ticker: "AMT",   nome: "American Tower",      setor: "Telecom" },
  { ticker: "CCI",   nome: "Crown Castle",        setor: "Telecom" },
  { ticker: "SBAC",  nome: "SBA Communications",  setor: "Telecom" },
  // Logística / Industrial
  { ticker: "PLD",   nome: "Prologis",            setor: "Logística" },
  { ticker: "STAG",  nome: "STAG Industrial",     setor: "Logística" },
  { ticker: "EGP",   nome: "EastGroup Properties",setor: "Logística" },
  { ticker: "FR",    nome: "First Industrial",    setor: "Logística" },
  // Data Centers
  { ticker: "EQIX",  nome: "Equinix",             setor: "Data Center" },
  { ticker: "DLR",   nome: "Digital Realty",      setor: "Data Center" },
  // Self-Storage
  { ticker: "PSA",   nome: "Public Storage",      setor: "Self-Storage" },
  { ticker: "EXR",   nome: "Extra Space Storage", setor: "Self-Storage" },
  { ticker: "CUBE",  nome: "CubeSmart",           setor: "Self-Storage" },
  { ticker: "NSA",   nome: "National Storage",    setor: "Self-Storage" },
  // Saúde
  { ticker: "WELL",  nome: "Welltower",           setor: "Saúde" },
  { ticker: "VTR",   nome: "Ventas",              setor: "Saúde" },
  { ticker: "DOC",   nome: "Healthpeak",          setor: "Saúde" },
  { ticker: "OHI",   nome: "Omega Healthcare",    setor: "Saúde" },
  { ticker: "MPW",   nome: "Medical Properties",  setor: "Saúde" },
  // Varejo (Net Lease / Mall)
  { ticker: "O",     nome: "Realty Income",       setor: "Varejo" },
  { ticker: "SPG",   nome: "Simon Property",      setor: "Shoppings" },
  { ticker: "REG",   nome: "Regency Centers",     setor: "Shoppings" },
  { ticker: "FRT",   nome: "Federal Realty",      setor: "Shoppings" },
  { ticker: "KIM",   nome: "Kimco Realty",        setor: "Shoppings" },
  { ticker: "BRX",   nome: "Brixmor Property",    setor: "Shoppings" },
  { ticker: "MAC",   nome: "Macerich",            setor: "Shoppings" },
  { ticker: "ADC",   nome: "Agree Realty",        setor: "Varejo" },
  { ticker: "EPR",   nome: "EPR Properties",      setor: "Entretenimento" },
  { ticker: "VICI",  nome: "VICI Properties",     setor: "Gaming" },
  // Residencial
  { ticker: "AVB",   nome: "AvalonBay",           setor: "Residencial" },
  { ticker: "EQR",   nome: "Equity Residential",  setor: "Residencial" },
  { ticker: "ESS",   nome: "Essex Property",      setor: "Residencial" },
  { ticker: "MAA",   nome: "Mid-America Apartment",setor: "Residencial" },
  { ticker: "UDR",   nome: "UDR",                 setor: "Residencial" },
  { ticker: "CPT",   nome: "Camden Property",     setor: "Residencial" },
  { ticker: "INVH",  nome: "Invitation Homes",    setor: "Residencial" },
  { ticker: "AMH",   nome: "American Homes 4 Rent",setor: "Residencial" },
  { ticker: "ELS",   nome: "Equity LifeStyle",    setor: "Residencial" },
  { ticker: "SUI",   nome: "Sun Communities",     setor: "Residencial" },
  // Office / Lab
  { ticker: "ARE",   nome: "Alexandria RE",       setor: "Office/Lab" },
  { ticker: "BXP",   nome: "Boston Properties",   setor: "Corporativo" },
  { ticker: "KRC",   nome: "Kilroy Realty",       setor: "Corporativo" },
  { ticker: "VNO",   nome: "Vornado Realty",      setor: "Corporativo" },
  { ticker: "SLG",   nome: "SL Green Realty",     setor: "Corporativo" },
  { ticker: "HPP",   nome: "Hudson Pacific",      setor: "Corporativo" },
  // Hotéis / Hospedagem
  { ticker: "HST",   nome: "Host Hotels",         setor: "Hotéis" },
  // Outros / Diversificado
  { ticker: "WPC",   nome: "W. P. Carey",         setor: "Diversificado" },
  { ticker: "IRM",   nome: "Iron Mountain",       setor: "Storage" },
  { ticker: "LAMR",  nome: "Lamar Advertising",   setor: "Outdoor" },
  { ticker: "COLD",  nome: "Americold Realty",    setor: "Logística" },
  { ticker: "GLPI",  nome: "Gaming & Leisure",    setor: "Gaming" },
];

export const CLASSES = [
  { id: "acoesBR", titulo: "15 Melhores Ações BR", lista: ACOES_BR, moeda: "BRL" },
  { id: "fiis",    titulo: "15 Melhores FIIs",      lista: FIIS,     moeda: "BRL" },
  { id: "acoesUS", titulo: "15 Melhores Ações US", lista: ACOES_US, moeda: "USD" },
  { id: "reits",   titulo: "15 Melhores REITs",     lista: REITS,    moeda: "USD" },
];
